project:
  type: website
  output-dir: docs

website:
  title: "Introducing spatial data science"
  sidebar: false
  page-navigation: true

format:
  html:
    theme: cyborg
    toc: false
    df-print: kable
    grid:
      sidebar-width: 200px
      body-width: 1200px
      margin-width: 100px
      gutter-width: 1.5rem