#### Geog 315 T2 2021
# Week 5 - Lab Assignment 3 Cluster analysis of commuting data
This assignment is quite open-ended. Here is the description:

** Run a cluster analysis of the provided Wellington commuter data and map the resulting clusters. Provide a short write up explaining how you did the analysis (not the commands used, focus instead on the number of clusters, variables included or excluded). Explain what you think the results tell us about the overall geographical structure of the Wellington Region. The overall write up should not be more than 2-3 pages (with this length *including* maps and diagrams if any).**

#### Things to consider
Here are a few things to be thinking about while working on this assignment.

+ How many clusters make sense? How many different kinds of 'place' are there in region like Wellington. Think about how you expect the region to break down into different kinds of place based on commuting patterns.
+ Try to provide verbal descriptions of the clusters you identify so that a reader can make sense of them without studying tables of data or complex charts.
+ Keep in mind that clusters are a *categorical* data type which has implications for the `style` to use when mapping them.
+ Consider if you want to retain all the supplied variables in the analysis. Maybe some are redundant, or you can get a clearer result by removing a few.
+ Consider if it is appropriate to rescale variables so they are expressed as proportions or percentages (you don't have to do this to get a good mark, but you should still _think_ about it and explain your choice with respect to this option.)

#### Assessment
Assessment will be based on the maps and any diagrams included, and an overall evaluation of your explanation of the analysis carried out and the discussion of what it shows. Pay equal attention to the quality of any maps or figures you include, and to the written discussion.

#### Submission
Prepare a PDF document that meets the requirements set out above. The whole document should only need to be 2-3 pages (maximum). Submit the PDF file to the dropbox provided on Blackboard. The due date is end of the day on **30 August**. Remember that you can export maps to PNG format images for inclusion in a Word document from RStudio.

Go [back to the overview page](README.md)
